config/routes.rb
Rails.application.routes.draw do
 root 'players#index'
 resources :players, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :gamestats
  has_many :stats, through: :gamestats

  validates :matchup_number, presence: true
  validates :home_team, presence: true
  validates :away_team, presence: true
  validates :year, presence: true
end

app/models/gamestat.rb
class Gamestat < ActiveRecord::Base
  belongs_to :game
  belongs_to :stat
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :playerstats
  has_many :stats, through: :playerstats

  validates :gsis, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthdate, presence: true
  validates :years_pro, presence: true
  validates :college, presence: true
end

app/models/playerstat.rb
class Playerstat < ActiveRecord::Base
  belongs_to :player
  belongs_to :stat
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :games

  validates :year, presence: true
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :player
  belongs_to :game
  has_many :games, through: :gamestats

  validates :stat_type, null: false
  validates :matchup_number, null: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all.order(:last_name, :first_name)
  end

  def show
    @player = Player.find(params[:id])
    @stats = @player.stats
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title> NFL Data</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>


  <body>
    <div className="large columns 12">
      <%= yield %>
    </div>
  </body>
</html>

app/views/players/index.html.erb
<h1>Players</h1>

  <% current_letter = "" %>
<ul>
  <% @players.each do |player| %>
    <% if player.last_name[0] != current_letter %>
      <% current_letter = player.last_name[0] %>
        <h1><%= current_letter %></h1>
        <hr>
        <li><% displayname = player.last_name + ", " + player.first_name %><%= link_to displayname, player%></li>
      <% else %>
        <li><% displayname = player.last_name + ", " + player.first_name %><%= link_to displayname, player%></li>
    <% end %>
  <% end %>
</ul>

app/views/players/show.html.erb
<h2> <%= @player.first_name %> <%= @player.last_name %>   </h2>
<ul>
  <li><h3>Years Pro: <%=@player.years_pro%></h3></li>
  <li><h3><%=@player.college%></h3></li>
</ul>

<h2> Player Total Stat </h2>
  <% passingyds = 0 %>
  <% passingtds = 0 %>

  <% receivingyds = 0 %>
  <% receivingtds = 0 %>

  <% rushingyds = 0 %>
  <% rushingtds = 0 %>


  <h4>Total Stat: Passing
    <% @stats.each do |stat| %>
      <% if stat.stat_type == "passing" %>
        <%passingyds += stat.yds %>
        <%passingtds += stat.tds %>
      <% end %>
    <% end %>
  <li> Passing Yards: <%= passingyds %> </li>
  <li> Passing Touchdowns: <%= passingtds %> </li>
</h4>

  <h4>Total Stat: Receiving
    <% @stats.each do |stat| %>
      <% if stat.stat_type == "receiving" %>
        <%receivingyds += stat.yds %>
        <%receivingtds += stat.tds %>
      <% end %>
    <% end %>
  <li> Receiving Yards: <%= receivingyds %> </li>
  <li> Receiving Touchdowns: <%= receivingtds %> </li>
</h4>

  <h4>Total Stat: Rushing
    <% @stats.each do |stat| %>
      <% if stat.stat_type == "rushing" %>
        <%rushingyds += stat.yds %>
        <%rushingtds += stat.tds %>
      <% end %>
    <% end %>
    <li> Rushing Yards: <%= rushingyds %> </li>
    <li> Rushing Touchdowns: <%= rushingtds %> </li>
  </h4>

  <h4> Game Stats </h4>
  <div>
  <% @stats.each do |stat| %>
    <% game = Game.find_by(matchup_number: stat.matchup_number) %>
      <% if !game.nil? %>
        <%= game.season_type %>(<%= game.year %>, Week <%= game.week %>, <%= game.wday %>) @<%=game.home_team %> vs <%= game.away_team %> <br>
        Stat Type: <%= stat.stat_type %> <br>
        Att: <%= stat.att %> <br>
        Comp: <%= stat.cmp %> <br>
        Yards: <%= stat.yds %> <br>
        Touchdowns: <%= stat.tds %> <br>
        Long: <%= stat.lng %> <br>
        Turnovers: <%= stat.turn_overs %> <br>
        <br>
        <br>
      <% end %>
  <% end %>
  </div>
<%= link_to 'Back to players', players_path %>

</div>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>